language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-digitaria' ]; then cd .. && eval "mv $currentfolder generator-digitaria" && cd generator-digitaria; fi

